import type { Metadata } from 'next'
import './globals.css'
import { Nunito } from "next/font/google"


export const metadata: Metadata = {
  title: 'Creative agency website',
  description: 'Generated by creative agency website',
}

const nunito = Nunito({ subsets: ['latin'], weight: ["400", "500", "600",  "700"] })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (   
    <html lang="en">
      <body  className={nunito.className} >{children}</body>
    </html>
  )
}
